/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Anthony Yanez (https://sketchfab.com/paulyanez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/youtube-logo-48e0a3c1c40a48c790dea5341d509f4e
Title: Youtube Logo
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/youtube.gltf");
  return (
    <group {...props} dispose={null}>
      <group scale={[1.242, 2.034, 0.621]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Youtube_Logo_01_-_Default_0"].geometry}
          material={materials["01_-_Default"]}
          position={[148.381, -48.827, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/youtube.gltf");
